version: '3.8'

services:
  tillywork:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
      - '3000:3000'
    env_file:
      - .env
    command: '/start.sh'
    depends_on:
      - db
  db:
    image: postgres:16.3-bullseye
    volumes:
      - tillywork:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${TW_DB_NAME}
      POSTGRES_USER: ${TW_DB_USERNAME}
      POSTGRES_PASSWORD: ${TW_DB_PASSWORD}
    restart: unless-stopped

volumes:
  tillywork:
